In [34]:
import numpy as np
import pandas as pd
X=np.array([[1, 40, 100], [1,20,100]])

In [19]:
np.transpose(X)

array([[  1,   1],
       [ 40,  20],
       [100, 100]])

In [60]:
theta = np.transpose(np.array([100, 20, 20]))

In [61]:
theta

array([100,  20,  20])

In [32]:
np.transpose(theta)

array([100,  20,  20])

In [20]:
theta1 = np.array([[100], [20], [20]])

In [28]:
np.transpose(theta1)

array([[100,  20,  20]])

In [27]:
X.dot(theta)

array([2900, 2500])

In [36]:
X = pd.DataFrame(X)

In [63]:
theta = pd.DataFrame(theta)


In [64]:
theta

0
0  100
1   20
2   20

In [65]:
X.dot(theta)

0
0  2900
1  2500