In [141]:
import numpy as np

In [27]:
v = np.zeros(10).reshape(10,1)

In [28]:
for i in range(10):
    v[i] = 2**(i+1)

In [15]:
indicies = range(5)

In [16]:
for i in indicies:
    print(i)

0
1
2
3
4


In [30]:
i=1
while i<=5:
    v[i] = 10
    i = i+1

In [31]:

v

array([[    2.],
       [   10.],
       [   10.],
       [   10.],
       [   10.],
       [   10.],
       [  128.],
       [  256.],
       [  512.],
       [ 1024.]])

In [32]:
i = 0
while True:
    v[i] = 99
    i += 1
    if i == 5:
        break

In [33]:
v

array([[   99.],
       [   99.],
       [   99.],
       [   99.],
       [   99.],
       [   10.],
       [  128.],
       [  256.],
       [  512.],
       [ 1024.]])

In [41]:
v[0] = 1

In [42]:
if v[0]==1:
    print('Val is one')
elif v[0] == 2:
    print('Val is two')
else:
    print('Val is neither one nor two')

Val is one


In [43]:
def squareThisNumber(x):
    return x**2

In [143]:
squareThisNumber(5)

NameError: name 'squareThisNumber' is not defined

In [152]:
import importlib
import foos

In [159]:
importlib.reload(foos)

<module 'foos' from '/Users/carioca/Dvlpt/prj/python/PyLearning/ang/foos.py'>

In [144]:
y1, y2 = foos.squareAndCubeThisNumber(5)

In [145]:
y1

25

In [146]:
y2

125

In [115]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [67]:
[a, b] = foos.squareAndCubeThisNumber(5)

In [147]:
foos.magic_square(5)

array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 13, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]])

In [148]:
X = np.array([[1,1], [1,2], [1,3]])

In [149]:
y = np.arange(1,4,1).reshape(3,1)

In [88]:
y[2] = 5

In [150]:
theta = np.array([0,1]).reshape(2,1)

In [76]:
theta

array([[0],
       [1]])

In [77]:
X.shape[0]

3

In [160]:
J = foos.costFunctionJ(X, y, theta)

In [140]:
J

2.3333333333333335

In [155]:
tarr = np.arange(6)

In [156]:
tarr**2

array([ 0,  1,  4,  9, 16, 25])

In [157]:
sum(tarr)

15

In [158]:
np.sum(tarr)

15