In [1]:
import numpy as np

In [9]:
u = (np.random.random(3).reshape(3,1)*10)

In [11]:
u = np.floor(u)

In [12]:
u

array([[ 9.],
       [ 5.],
       [ 1.]])

In [13]:
v = (np.random.random(3).reshape(3,1)*10)

In [14]:
v = np.floor(v)

In [15]:
v

array([[ 6.],
       [ 4.],
       [ 5.]])

In [16]:
w = (np.random.random(3).reshape(3,1)*10)

In [17]:
w = np.floor(w)

In [18]:
w

array([[ 5.],
       [ 2.],
       [ 8.]])

In [19]:
2*w

array([[ 10.],
       [  4.],
       [ 16.]])

In [20]:
2+w

array([[  7.],
       [  4.],
       [ 10.]])

In [21]:
v+w

array([[ 11.],
       [  6.],
       [ 13.]])

In [34]:
a = np.arange(12).reshape(2,6)

In [35]:
b = np.arange(10,16,1)

In [36]:
a.dot(b)

array([205, 655])

In [40]:
c = np.arange(6) 

In [41]:
b+c

array([10, 12, 14, 16, 18, 20])

In [45]:
a/4

array([[ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25],
       [ 1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75]])