In [1]:
import numpy as np

In [3]:
A = np.arange(1,7,1).reshape(3,2)

In [5]:
B = np.arange(11,17,1).reshape(3,2)

In [6]:
C = np.array([[1,1],[2,2]])

In [10]:
A.dot(C)

array([[ 5,  5],
       [11, 11],
       [17, 17]])

In [12]:
A*B

array([[11, 24],
       [39, 56],
       [75, 96]])

In [13]:
A**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [35]:
v = np.arange(1,4,1).reshape(3,1)

In [17]:
1/v

array([[ 1.        ],
       [ 0.5       ],
       [ 0.33333333]])

In [19]:
1/A

array([[ 1.        ,  0.5       ],
       [ 0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667]])

In [21]:
from math import log, exp

In [23]:
np.log(v)

array([[ 0.        ],
       [ 0.69314718],
       [ 1.09861229]])

In [24]:
np.exp(v)

array([[  2.71828183],
       [  7.3890561 ],
       [ 20.08553692]])

In [26]:
np.abs(v)

array([[1],
       [2],
       [3]])

In [28]:
np.abs([-1,-2])

array([1, 2])

In [29]:
-v

array([[-1],
       [-2],
       [-3]])

In [30]:
v = v+1

In [36]:
v = v + np.ones(3, dtype=int).reshape(3,1)

In [37]:
v

array([[2],
       [3],
       [4]])

In [43]:
A.T.T

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a = np.array([1, 15, 2, .5])

max(a)

In [46]:
max(a)

15.0

In [52]:

val = np.max(a)

In [50]:
ind = np.argmax(a)

In [54]:
val, ind

(15.0, 1)

In [59]:
np.amax(A, axis=1)

array([2, 4, 6])

In [61]:
a < 3

array([ True, False,  True,  True], dtype=bool)

In [66]:
np.where(a<3)

(array([0, 2, 3]),)

In [77]:
[r,c] = np.where(A>3)

In [78]:
r

array([1, 2, 2])

In [80]:
c

array([1, 0, 1])

In [81]:
sum(a)

18.5

In [82]:
np.prod(a)

15.0

In [83]:
np.floor(a)

array([  1.,  15.,   2.,   0.])

In [84]:
np.ceil(a)

array([  1.,  15.,   2.,   1.])

In [107]:
np.maximum(np.random.random(5), np.random.random(5))

array([ 0.91998367,  0.88945112,  0.10426162,  0.74826622,  0.88995854])

In [111]:
np.amax(A, axis=0)

array([5, 6])

In [112]:
np.amax(A)

6

In [115]:
np.sum(A,0)

array([ 9, 12])

In [124]:
def magic_square(N):

    magic_square = np.zeros((N,N), dtype=int)

    n = 1
    i, j = 0, N//2

    while n <= N**2:
        magic_square[i, j] = n
        n += 1
        newi, newj = (i-1) % N, (j+1)% N
        if magic_square[newi, newj]:
            i += 1
        else:
            i, j = newi, newj

    return magic_square

In [125]:
magic_square(3)

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [126]:
A = magic_square(3)

In [128]:
np.amax(A)

9

In [129]:
np.amax(A, axis=0)

array([8, 9, 7])

In [130]:
np.amax(A,axis=1)

array([8, 7, 9])

In [131]:
np.argmax(A,axis=1)

array([0, 2, 1])

In [136]:
np.amax(A.flatten())

9

In [138]:
A.flatten()

array([8, 1, 6, 3, 5, 7, 4, 9, 2])

In [139]:
A = magic_square(9)


In [141]:
np.sum(A, axis=0)

array([369, 369, 369, 369, 369, 369, 369, 369, 369])

In [142]:
np.sum(A, axis=1)

array([369, 369, 369, 369, 369, 369, 369, 369, 369])

In [144]:
np.eye(9)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [147]:
A * (np.eye(9))

array([[ 47.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  68.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   8.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  20.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  41.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  62.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  74.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,  14.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  35.]])

In [150]:
np.sum(A*np.flipud(np.eye(9)))

369.0

In [149]:
np.flipud(np.eye(9))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [151]:
A = magic_square(3)

In [155]:
type(A)

numpy.ndarray

In [157]:

A.__invert__()

array([[ -9,  -2,  -7],
       [ -4,  -6,  -8],
       [ -5, -10,  -3]])

In [158]:
A

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [159]:
A.dot(A.__invert__())

array([[-106,  -82,  -82],
       [ -82, -106,  -82],
       [ -82,  -82, -106]])

In [161]:
from numpy.linalg import inv, pinv

In [162]:
inv(A)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [163]:
pinv(A, 1e-15)

array([[ 0.14722222, -0.14444444,  0.06388889],
       [-0.06111111,  0.02222222,  0.10555556],
       [-0.01944444,  0.18888889, -0.10277778]])

In [175]:
A.dot(pinv(A, 1e-1))

array([[  1.00000000e+00,  -1.19904087e-14,   6.55031585e-15],
       [  1.11022302e-16,   1.00000000e+00,   1.11022302e-16],
       [ -5.88418203e-15,   1.23789867e-14,   1.00000000e+00]])

In [169]:
A.dot(inv(A))

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [ -5.55111512e-17,   1.00000000e+00,   1.11022302e-16],
       [ -3.46944695e-17,   5.55111512e-17,   1.00000000e+00]])