In [55]:
import numpy as np

In [3]:
A = np.arange(1, 7, 1).reshape(3,2)

In [5]:
A


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
sz = A.shape

In [13]:
np.array(sz).shape

(2,)

In [19]:
A.shape[1]

2

In [21]:
 max(A.shape)

3

In [46]:
import pandas as pd

In [23]:
features = pd.read_csv("featuresX.dat.txt", sep="\t", header=None, names=["size", "bedrooms"])

In [22]:
priceY = pd.read_csv("priceY.dat.txt", header=None, names=["price"])

In [24]:
dataset = pd.concat([features, priceY], axis=1)

In [26]:
priceY.shape

(27, 1)

In [40]:
dataset.to_csv("dataset.csv", index=False)

In [45]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [47]:
dataset=pd.read_csv("dataset.csv")

In [53]:
v = dataset[1:10]

In [97]:
A = np.arange(1,7,1).reshape(3,2)

In [65]:
A.transpose()[1]

array([2, 4, 6])

In [78]:
A[[0,2]]

array([[1, 2],
       [5, 6]])

In [85]:
A[:,1]

array([2, 4, 6])

In [109]:
A

array([[ 1, 10],
       [ 3, 11],
       [ 5, 12]])

In [106]:
A[:,1] = np.array([10,11,12])

In [115]:
A = np.append(A, np.array([101,102,103]).reshape(3,1), axis=1)

In [116]:
A

array([[  1,  10, 101],
       [  3,  11, 102],
       [  5,  12, 103]])

In [113]:
B=np.array([101,102,103])

In [121]:
A.flatten()

array([  1,  10, 101,   3,  11, 102,   5,  12, 103])