In [30]:
import numpy as np
data = np.loadtxt('ex1data2.txt', delimiter=',')
X = data[:,:2]
y = data[:,2]
m = y.size
y = y.reshape(m,1); X = X.reshape(m,2)
X = np.append(np.ones(m).reshape(m,1), X, axis=1)


In [14]:
import costFunctionJ
import gradientDescent

In [37]:
iterations = 1500
alpha = .01
theta = np.zeros(3).reshape(3,1)

In [ ]:
def featureNormalize(X):
    X_norm = X
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_norm = 
    return X_norm, mu, sigma

In [49]:
np.std(X[:10], axis=0)

array([   0.        ,  508.1789055 ,    0.53851648])

In [54]:
X[:10, 1:3] - np.mean(X[:10, 1:3], axis=0) / np.std(X[:10, 1:3], axis=0)

array([[  2.10039103e+03,  -2.75655548e+00],
       [  1.59639103e+03,  -2.75655548e+00],
       [  2.39639103e+03,  -2.75655548e+00],
       [  1.41239103e+03,  -3.75655548e+00],
       [  2.99639103e+03,  -1.75655548e+00],
       [  1.98139103e+03,  -1.75655548e+00],
       [  1.53039103e+03,  -2.75655548e+00],
       [  1.42339103e+03,  -2.75655548e+00],
       [  1.37639103e+03,  -2.75655548e+00],
       [  1.49039103e+03,  -2.75655548e+00]])

In [56]:
X[:10, 1:3]

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [38]:
costFunctionJ.costFunctionJ(X, y, theta)

array([  6.55915481e+10])

In [31]:
test_theta, hstry = gradientDescent.gradientDescent(X, y, theta, alpha, iterations)

C:\Users\KFrolov\Documents\Inno_Internship\Inno_Internship\Python_prj\PyLearning\ang\exercise\costFunctionJ.py:5: RuntimeWarning: overflow encountered in add
  return sum(sqrErrors**2)/2/m
C:\Users\KFrolov\Documents\Inno_Internship\Inno_Internship\Python_prj\PyLearning\ang\exercise\costFunctionJ.py:5: RuntimeWarning: overflow encountered in square
  return sum(sqrErrors**2)/2/m
C:\Users\KFrolov\Documents\Inno_Internship\Inno_Internship\Python_prj\PyLearning\ang\exercise\gradientDescent.py:10: RuntimeWarning: overflow encountered in multiply
  temp_theta[j] = theta[j] - alpha / m * ((X.dot(theta) - y) * X[:,j].reshape(m,1)).sum()


In [40]:
pre = X.dot(theta)

In [41]:
pre[:10]

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])