In [2]:
import numpy as np

In [3]:
rr = np.array([(1,2), 
              (3,4)], dtype = complex)

In [5]:
rr

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [23]:
rr1 = np.ones((1,2,6), dtype = np.int16)

In [25]:
rr1

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int16)

In [26]:
rr1[0]

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [28]:
rng = np.arange(1, 2, .1)

In [39]:
rng.ndim

1

In [44]:
from numpy import pi

In [49]:
linear_arr = np.linspace(0, 2*pi, 100)
f = np.sin(linear_arr)

In [50]:
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,