In [2]:
import numpy as np

In [3]:
rr = np.array([(1,2), 
              (3,4)], dtype = complex)

In [5]:
rr

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [23]:
rr1 = np.ones((1,2,6), dtype = np.int16)

In [25]:
rr1

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int16)

In [26]:
rr1[0]

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)