In [11]:
import numpy as np
arr = np.linspace(5, 10, 10)

In [13]:
arr

array([  5.        ,   5.55555556,   6.11111111,   6.66666667,
         7.22222222,   7.77777778,   8.33333333,   8.88888889,
         9.44444444,  10.        ])

In [17]:
arr1 = np.ones((1,10), dtype = complex)

In [18]:
arr1

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j]])

In [19]:
arr2 = arr * arr1

In [26]:
arr2 = 10*np.sin(arr1 * arr)

In [46]:
arr2

array([[ -8.58924275+2.5j,  -5.65101515+2.5j,  -0.71226280+2.5j,
          4.74151231+2.5j,   9.06989710+2.5j,  10.97097891+2.5j,
          9.87294108+2.5j,   6.10605678+2.5j,   0.80334784+2.5j,
         -4.44021111+2.5j]])

In [45]:
arr2 > 5 + 5j

array([[False, False, False, False,  True,  True,  True,  True, False,
        False]], dtype=bool)

In [37]:
arr2 = arr2+1.5j