In [1]:
import numpy as np

In [42]:
a = np.arange(15)
type(a)

numpy.ndarray

In [47]:
a_rshp = a.reshape(3,5)
type(a_rshp[2])

numpy.ndarray

In [40]:
print(a_rshp)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
c = np.array([1,2])
b = np.array([np.array([1,2])])

In [26]:
b.dtype
b.ndim

2

In [28]:
d = np.array([1,2,3])
e = np.array([4,5])
f = np.array([6,7,8])

In [63]:
g = np.array([[1,2], [3,4], [5,6]])
print(type(g[0]))
h = [1,2]
print(type(h))

<class 'numpy.ndarray'>
<class 'list'>


In [56]:
print(g)

[[1 2]
 [3 4]]


In [66]:
print(g.shape)
print(g.size)

(3, 2)
6


In [68]:
g.data

In [70]:
g.itemsize

8

In [74]:
g.dtype

dtype('int64')

In [82]:
i = np.array([((1,2),(3,4)),
              ((5,6),(7,8))], dtype = complex)

In [80]:
type(i[0])

numpy.ndarray

In [83]:
i.shape

(2, 2, 2)

In [84]:
i

array([[[ 1.+0.j,  2.+0.j],
        [ 3.+0.j,  4.+0.j]],

       [[ 5.+0.j,  6.+0.j],
        [ 7.+0.j,  8.+0.j]]])